### ISSUE TITLE
to get deps/build.jl working

### ISSUE THREAD

**Issue by TeroFrondelius** [JuliaFEM/CalculiX.jl#1]
@JuliaFEM/owners can you test, on a linux machine, if the build.jl works. Basically commands:

``` julia
julia > Pkg.clone("git@github.com:JuliaFEM/CalculiX.jl.git")

julia > Pkg.build("CalculiX")
```

should do the trick or if not working please try:

``` bash
$ cd CalculiX/deps

$ julia build.jl
```

**Comment by TeroFrondelius** [comment]
Now it should work again.

**Comment by ahojukka5** [comment]
Lots of comments there :)

**Comment by TeroFrondelius** [comment]
I believe this works now.
